#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================
minio:
  endpoint: http://106.54.241.247:9000
  accessKey: sugertzy
  secretKey: sugertzy