server:
  port: 8086 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境

mybatis:
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml

mq-consumer: # MQ 消费者
  follow-unfollow: # 关注、取关
    rate-limit: 5000 # 每秒限流阈值
